# Generated by Django 4.2.3 on 2023-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
            ],
        ),
    ]

